# coding: utf-8

"""
    Learner API

    This API is used to interact with the data stored in the TLA Learner Profile database.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import learner_inferences_client
from learner_inferences_client.models.person import Person  # noqa: E501
from learner_inferences_client.rest import ApiException


class TestPerson(unittest.TestCase):
    """Person unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPerson(self):
        """Test Person"""
        # FIXME: construct object with mandatory attributes with example values
        # model = learner_inferences_client.models.person.Person()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
