# coding: utf-8

"""
    Recommender API

    This is the API definition for the Recommender service.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import recommenderclient
from recommenderclient.models.recommendation_row import RecommendationRow  # noqa: E501
from recommenderclient.rest import ApiException


class TestRecommendationRow(unittest.TestCase):
    """RecommendationRow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecommendationRow(self):
        """Test RecommendationRow"""
        # FIXME: construct object with mandatory attributes with example values
        # model = recommenderclient.models.recommendation_row.RecommendationRow()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
