# coding: utf-8

"""
    Recommender API

    This is the API definition for the Recommender service.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import recommenderclient
from recommenderclient.models.recommended_activity import RecommendedActivity  # noqa: E501
from recommenderclient.rest import ApiException


class TestRecommendedActivity(unittest.TestCase):
    """RecommendedActivity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecommendedActivity(self):
        """Test RecommendedActivity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = recommenderclient.models.recommended_activity.RecommendedActivity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
