# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LearnerGoals(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, goals: List[object]=None):  # noqa: E501
        """LearnerGoals - a model defined in Swagger

        :param goals: The goals of this LearnerGoals.  # noqa: E501
        :type goals: List[object]
        """
        self.swagger_types = {
            'goals': List[object]
        }

        self.attribute_map = {
            'goals': 'goals'
        }

        self._goals = goals

    @classmethod
    def from_dict(cls, dikt) -> 'LearnerGoals':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LearnerGoals of this LearnerGoals.  # noqa: E501
        :rtype: LearnerGoals
        """
        return util.deserialize_model(dikt, cls)

    @property
    def goals(self) -> List[object]:
        """Gets the goals of this LearnerGoals.

        The new goals for the learner  # noqa: E501

        :return: The goals of this LearnerGoals.
        :rtype: List[object]
        """
        return self._goals

    @goals.setter
    def goals(self, goals: List[object]):
        """Sets the goals of this LearnerGoals.

        The new goals for the learner  # noqa: E501

        :param goals: The goals of this LearnerGoals.
        :type goals: List[object]
        """
        if goals is None:
            raise ValueError("Invalid value for `goals`, must not be `None`")  # noqa: E501

        self._goals = goals
