# coding: utf-8

"""
    Asset API

    This API is used to interact with the data stored in the TLA Activity Index database.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import activity_index_client
from activity_index_client.models.person import Person  # noqa: E501
from activity_index_client.rest import ApiException


class TestPerson(unittest.TestCase):
    """Person unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPerson(self):
        """Test Person"""
        # FIXME: construct object with mandatory attributes with example values
        # model = activity_index_client.models.person.Person()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
