---

- name: "Initialize Platform-Specific Postfix Configuration"
  tags: always
  set_fact:
    postfix_platform_specific: "{{ postfix_defaults | combine(_postfix_platform_specific_defaults[ansible_distribution][ansible_distribution_release] | default({}), recursive=True) }}"

- name: "Initialize Postfix Configuration"
  tags: always
  set_fact:
    postfix: "{{ postfix_platform_specific | combine(postfix | default({}), recursive=True) }}"

- name: "Debug Role Configuration"
  tags: always
  debug:
    msg: "{{ postfix }}"

- include: "postfix-{{ ansible_os_family }}.yml"
