# coding: utf-8

"""
    Asset API

    This API is used to interact with the data stored in the TLA Activity Index database.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CompetencyAssociations(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'competency': 'str',
        'activities': 'list[str]'
    }

    attribute_map = {
        'competency': 'competency',
        'activities': 'activities'
    }

    def __init__(self, competency=None, activities=None):  # noqa: E501
        """CompetencyAssociations - a model defined in Swagger"""  # noqa: E501

        self._competency = None
        self._activities = None
        self.discriminator = None

        self.competency = competency
        self.activities = activities

    @property
    def competency(self):
        """Gets the competency of this CompetencyAssociations.  # noqa: E501

        URL reference to TLO or ELO  # noqa: E501

        :return: The competency of this CompetencyAssociations.  # noqa: E501
        :rtype: str
        """
        return self._competency

    @competency.setter
    def competency(self, competency):
        """Sets the competency of this CompetencyAssociations.

        URL reference to TLO or ELO  # noqa: E501

        :param competency: The competency of this CompetencyAssociations.  # noqa: E501
        :type: str
        """
        if competency is None:
            raise ValueError("Invalid value for `competency`, must not be `None`")  # noqa: E501

        self._competency = competency

    @property
    def activities(self):
        """Gets the activities of this CompetencyAssociations.  # noqa: E501

        IDs of activities associated with the TLO/ELO  # noqa: E501

        :return: The activities of this CompetencyAssociations.  # noqa: E501
        :rtype: list[str]
        """
        return self._activities

    @activities.setter
    def activities(self, activities):
        """Sets the activities of this CompetencyAssociations.

        IDs of activities associated with the TLO/ELO  # noqa: E501

        :param activities: The activities of this CompetencyAssociations.  # noqa: E501
        :type: list[str]
        """
        if activities is None:
            raise ValueError("Invalid value for `activities`, must not be `None`")  # noqa: E501

        self._activities = activities

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CompetencyAssociations):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
