---

- name: Install Pip
  command: apt-get -y install python3-pip

- name: Install PyMongo
  command: python3 -m pip install pymongo

- name: Install Flask
  command: python3 -m pip install flask

- name: Install Connexion
  command: python3 -m pip install connexion

- name: Copy config.py template file
  template:
    src: "config.py.j2"
    dest: "/vagrant/activity-index/server/activity_index_server/config.py"

- name: Install Activity Index Server Python Package in Develop Mode
  command: python3 -m pip install -e /vagrant/activity-index/server/

- name: Install Activity Client Python Package in Develop Mode
  command: python3 -m pip install -e /vagrant/activity-index/clients/python/

- name: "Copy Activity Index Files to Server"
  copy:
    src: /vagrant/activity-index
    dest: /activity-index

- name: Make /var/www/activity-index Directory
  file:
    path: /var/www/activity-index
    state: directory

- name: "Enable apache2 Headers Module"
  shell: "a2enmod headers"
  become: true

- name: Copy WSGI file to /var/www/activity-index
  copy:
    src: "activity_index.wsgi"
    dest: "/var/www/activity-index"

- name: Copy Apache config file
  template:
    src:  "activity-index.j2"
    dest: "/etc/apache2/sites-available/activity-index.conf"
  notify: restart apache

- name: "Add Listening Port to ports.conf"
  lineinfile:
    dest: "/etc/apache2/ports.conf"
    line: "Listen {{ tla_config.activity_index.port }}"
  notify: restart apache

- name: "Enable Activity Index VirtualHost"
  shell: "a2ensite activity-index"
  args:
    creates: "/etc/apache2/sites-enabled/activity-index.conf"
  notify: restart apache

- meta: flush_handlers
