# coding: utf-8

"""
    Recommender UI Support Service API

    This API is used to interact with the data stored in the Recommnder UI Support Service database.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import recommenderuisupportclient
from recommenderuisupportclient.api.tokens_api import TokensApi  # noqa: E501
from recommenderuisupportclient.rest import ApiException


class TestTokensApi(unittest.TestCase):
    """TokensApi unit test stubs"""

    def setUp(self):
        self.api = recommenderuisupportclient.api.tokens_api.TokensApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_learner_tokens(self):
        """Test case for delete_learner_tokens

        Deletes a learner's tokens  # noqa: E501
        """
        pass

    def test_get_learner_tokens(self):
        """Test case for get_learner_tokens

        Obtains the tokens and activity unlock threshold for a learner  # noqa: E501
        """
        pass

    def test_post_learner_tokens(self):
        """Test case for post_learner_tokens

        Adds a new learner to the database with no tokens  # noqa: E501
        """
        pass

    def test_update_learner_tokens(self):
        """Test case for update_learner_tokens

        Updates a learner's tokens or activity unlock threshold  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
