# coding: utf-8

"""
    Recommender UI Support Service API

    This API is used to interact with the data stored in the Recommnder UI Support Service database.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import recommenderuisupportclient
from recommenderuisupportclient.api.learner_preferences_api import LearnerPreferencesApi  # noqa: E501
from recommenderuisupportclient.rest import ApiException


class TestLearnerPreferencesApi(unittest.TestCase):
    """LearnerPreferencesApi unit test stubs"""

    def setUp(self):
        self.api = recommenderuisupportclient.api.learner_preferences_api.LearnerPreferencesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_learner_preferences(self):
        """Test case for delete_learner_preferences

        Deletes a learner's preferences  # noqa: E501
        """
        pass

    def test_post_learner_preferences(self):
        """Test case for post_learner_preferences

        Stores a learner's preferences  # noqa: E501
        """
        pass

    def test_update_learner_preferences(self):
        """Test case for update_learner_preferences

        Updates a learner's preferences  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
