# coding: utf-8

"""
    Recommender UI Support Service API

    This API is used to interact with the data stored in the Recommender UI Support Service database.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import recommenderuisupportclient
from recommenderuisupportclient.api.ao_image_api import AOImageApi  # noqa: E501
from recommenderuisupportclient.rest import ApiException


class TestAOImageApi(unittest.TestCase):
    """AOImageApi unit test stubs"""

    def setUp(self):
        self.api = recommenderuisupportclient.api.ao_image_api.AOImageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_ao_image(self):
        """Test case for get_ao_image

        Obtains the AO Image  # noqa: E501
        """
        pass

    def test_post_ao_image(self):
        """Test case for post_ao_image

        Stores the AO Image  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
