# coding: utf-8

"""
    Recommender UI Support Service API

    This API is used to interact with the data stored in the Recommnder UI Support Service database.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import recommenderuisupportclient
from recommenderuisupportclient.api.page_state_api import PageStateApi  # noqa: E501
from recommenderuisupportclient.rest import ApiException


class TestPageStateApi(unittest.TestCase):
    """PageStateApi unit test stubs"""

    def setUp(self):
        self.api = recommenderuisupportclient.api.page_state_api.PageStateApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_page_state(self):
        """Test case for delete_page_state

        Deletes the page state for a user session  # noqa: E501
        """
        pass

    def test_get_page_state(self):
        """Test case for get_page_state

        Obtains the page state for a user session  # noqa: E501
        """
        pass

    def test_post_page_state(self):
        """Test case for post_page_state

        Stores the page state for a new user session  # noqa: E501
        """
        pass

    def test_update_page_state(self):
        """Test case for update_page_state

        Updates the page state for a user session  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
