---

- name: "Prepare Logging/Monitoring Tools"
  hosts: monitored
  remote_user: root
  become: yes
  become_method: sudo

  roles:

    # Log stat script will produce entry every 5 minutes"
    - role: log_stats
      tags: log_stats
      log_stats: "{{ log_stats_cfg }}"

    # Set up NTP Daemon to regularly update clock
    - role: ntpd
      ntpd:
        # Use servers from the NTP Pool Project. Approved by Ubuntu Technical Board
        # on 2011-02-08 (LP: #104525). See http://www.pool.ntp.org/join.html for
        # more information.
        servers:
          - "0.ubuntu.pool.ntp.org"
          - "1.ubuntu.pool.ntp.org"
          - "2.ubuntu.pool.ntp.org"
          - "3.ubuntu.pool.ntp.org"
          # Use Ubuntu's ntp server as a fallback.
          - "ntp.ubuntu.com"

    # Install the tcpdump service for logging traffic
    - role: tcpdump_service
      tcpdump_service: "{{ tcpdump }}"
