---

# Role Dependencies:
#  - php
#  - apache2
#  - mongodb
#  - postfix

learning_locker_defaults:
  web_root:   "/var/www/learninglocker"
  root_url:   "http://{{ default_hostname | default('localhost') }}"
  port:       8001
  version:    "1.15.1"

  app_cfg:      "app.php.j2"
  database_cfg: "database.php.j2"
  mail_cfg:     "mail.php.j2"

  vhost_conf: "learning-locker.conf.j2"
  owner:      "{{ apache2.owner }}"
  group:      "{{ apache2.group }}"

  apt:
    update_cache:     true
    cache_valid_time: 3600

  download_cache_dir: "{{ download_cache_dir | default('/tmp') }}"
  init_cache_dir:     "{{ init_cache_dir | default('/var/cache/ansible') }}/learning_locker"

  phpenmod: "phpenmod"
  php_modules_to_enable:
    - "mcrypt"

  dependencies:
    - "rng-tools"
    - "curl"
    - "php5.6-fpm"
    - "php5.6-mcrypt"
    - "php5.6-cli"
    - "php5.6-xcache"
    - "php5.6-curl"
    - "php5.6-mongo"
    - "php5.6-mongo"
    - "php5.6-zip"
    - "libapache2-mod-php5.6"

_learning_locker_platform_specific_defaults:
  Ubuntu:
    trusty: {}
      #phpenmod: "php5enmod"
      #php_modules_to_enable:
      #  - "mcrypt"
      #dependencies:
      #  - "rng-tools"
      #  - "curl"
      #  - "php5-fpm"
      #  - "php5-mcrypt"
      #  - "php5-cli"
      #  - "php5-xcache"
      #  - "php5-curl"
      #  - "php5-pgsql"
      #  - "php5-mongo"
      #  - "php-xml-parser"
      #  #- "php-zip"
    xenial: {}
      #phpenmod: "phpenmod"
      #php_modules_to_enable:
      #  - "mcrypt"
      #dependencies:
      #  - "rng-tools"
      #  - "curl"
      #  - "php7.0-fpm"
      #  - "php7.0-mcrypt"
      #  - "php7.0-cli"
      #  #- "php7.0-xcache"
      #  - "php7.0-curl"
      #  - "php-mongodb"
      #  - "php7.0-pgsql"
      #  - "php7.0-xml"
      #  - "php7.0-zip"
