# coding: utf-8

"""
    CASS API

    This API is used to interact with the data stored in the CASS database.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cass_client
from cass_client.models.framework import Framework  # noqa: E501
from cass_client.rest import ApiException


class TestFramework(unittest.TestCase):
    """Framework unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFramework(self):
        """Test Framework"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cass_client.models.framework.Framework()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
